### ISSUE TITLE
Edit 'create a profile page'

### ISSUE THREAD

**Issue by Kaisuke23** [314gb/warrior-gamers#6]
creation of the 'profile page' page with details discussed on discord.

**Comment by tevintsales** [comment]
Edit information taken on create profile to fit Warrior Buddies needs.
- Add steam 
- Add battle net tag

**Comment by tevintsales** [comment]
Created a gamer-profile.html page along with gamer-profile.js.
Also created a Games Collection and GamerProfile collection for the server database.
